### ISSUE TITLE
Aview AI pages

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aview-ai#1]
how is this the first issue on this repo lmao. @d-huliu here is the [figma link](https://www.figma.com/design/PMfG3eyLRvDwQ2iG2QXUmK?node-id=3090-18488#886757031). let me know if you have further questions

**Comment by d-huliu** [comment]
lmao

**Comment by Vicopem01** [comment]
@chandhuDev , let's hop on this to get it out as soon as possible.

**Comment by chandhuDev** [comment]
@Vicopem01 probably this is the one repo by fixing only one issue would complete the desired features , don't need to create any issue LOL
